import { ToolCategory } from '@/types/tools';
import {
  ArrowLeftRight,
  Braces,
  Code,
  FileCode,
  FileText,
  GitCompare,
  Hash,
  Key,
  Link,
  List,
  Lock,
  MapPin,
  Minimize2,
  Network,
  QrCode,
  RefreshCw,
  ScanLine,
  ScanSearch,
  Search,
  Timer,
  Unlock,
  Wrench,
  Info,
  Binary,
  Database,
  ClipboardPaste,
  type LucideIcon
} from 'lucide-react';

// Icon mapping for tools
export const toolIcons: Record<string, LucideIcon> = {
  'lorem-ipsum': FileText,
  'json-formatter': Braces,
  'xml-formatter': Code,
  'sql-formatter': Database,
  'uuid-generator': Hash,
  'qr-code-generator': QrCode,
  'qr-code-decoder': ScanSearch,
  'qr-code-scanner': ScanLine,
  'url-encoder': Link,
  'url-decoder': Unlock,
  'cron-parser': Wrench,
  'cidr-analyzer': Network,
  'ip-to-cidr-converter': Network,
  'ip-checker': MapPin,
  'diff-checker': GitCompare,
  'html-to-markdown': ClipboardPaste,
  'text-minifier': Minimize2,
  'timestamp-converter': Timer,
  'list-comparison': List,
  'list-converter': ArrowLeftRight,
  'json-path-finder': ScanSearch,
  'xml-path-finder': ScanSearch,
  'yaml-path-finder': ScanSearch,
  'json-schema-generator': FileCode,
  'schema-converter': ArrowLeftRight,
  'jwt-decoder': Key,
  'jwt-encoder': Lock,
  'data-format-converter': RefreshCw,
  'regex-tester': Search,
  'system-info': Info,
  'number-base-converter': Binary,
  'base-encoder': Binary,
  'hash-generator': Hash,
};

export const toolCategories: ToolCategory[] = [
  {
    id: 'text-tools',
    name: 'Text Tools',
    icon: '📝',
    color: 'blue',
    description: 'Text generation and manipulation tools',
    tools: [
      {
        id: 'lorem-ipsum',
        name: 'Lorem Ipsum Generator',
        description: 'Generate placeholder text in Latin or Bacon Ipsum',
        category: 'text-tools',
        icon: '📄',
        isPopular: true,
        path: '/tools/text-tools/lorem-ipsum',
        component: 'LoremIpsumGenerator',
        supportsDesktop: true,
        supportsMobile: true,
      },
      {
        id: 'regex-tester',
        name: 'Regex Tester',
        description: 'Test and debug regular expressions with real-time matching, group extraction, and code generation',
        category: 'text-tools',
        icon: '🔍',
        isPopular: true,
        path: '/tools/text-tools/regex-tester',
        component: 'RegexTester',
        supportsDesktop: true,
        supportsMobile: true,
      },
      {
        id: 'diff-checker',
        name: 'Diff Checker',
        description: 'Compare two texts side-by-side and highlight differences with syntax highlighting',
        category: 'text-tools',
        icon: '📊',
        isPopular: true,
        path: '/tools/text-tools/diff-checker',
        component: 'DiffChecker',
        supportsDesktop: true,
        supportsMobile: true,
        desktopRecommended: true,
      },
      {
        id: 'html-to-markdown',
        name: 'HTML to Markdown',
        description: 'Convert HTML copied from websites into GitHub-flavored Markdown',
        category: 'text-tools',
        icon: '📋',
        isPopular: false,
        path: '/tools/text-tools/html-to-markdown',
        component: 'HtmlToMarkdown',
        supportsDesktop: true,
        supportsMobile: true,
      },
      {
        id: 'text-minifier',
        name: 'Text Minifier',
        description:
          'Collapse redundant whitespace in plain text—single-line or per-line—with optional CRLF normalization and empty-line removal',
        category: 'text-tools',
        icon: '⏬',
        isPopular: false,
        path: '/tools/text-tools/text-minifier',
        component: 'TextMinifier',
        supportsDesktop: true,
        supportsMobile: true,
      },
    ],
  },
  {
    id: 'formatters',
    name: 'Formatters',
    icon: '🔧',
    color: 'green',
    description: 'Code and data formatting tools',
    tools: [
          {
            id: 'json-formatter',
            name: 'JSON Formatter',
            description: 'Format and beautify JSON data',
            category: 'formatters',
            icon: '{ }',
            isPopular: true,
            path: '/tools/formatters/json-formatter',
            component: 'JsonFormatter',
            supportsDesktop: true,
            supportsMobile: true,
          },
      {
        id: 'xml-formatter',
        name: 'XML Formatter',
        description: 'Format and beautify XML data',
        category: 'formatters',
        icon: '< >',
        isPopular: false,
        path: '/tools/formatters/xml-formatter',
        component: 'XmlFormatter',
        supportsDesktop: true,
        supportsMobile: true,
      },
      {
        id: 'sql-formatter',
        name: 'SQL Formatter',
        description: 'Validate, beautify, and minify SQL for many dialects',
        category: 'formatters',
        icon: 'SQL',
        isPopular: false,
        path: '/tools/formatters/sql-formatter',
        component: 'SqlFormatter',
        supportsDesktop: true,
        supportsMobile: true,
      },
    ],
  },
  {
    id: 'cryptography',
    name: 'Cryptography & Security',
    icon: '🔐',
    color: 'red',
    description: 'Security and cryptographic tools',
    tools: [
      {
        id: 'uuid-generator',
        name: 'UUID Generator',
        description: 'Generate unique identifiers in v1, v4, and v5 formats',
        category: 'cryptography',
        icon: '🆔',
        isPopular: true,
        path: '/tools/cryptography/uuid-generator',
        component: 'UuidGenerator',
        supportsDesktop: true,
        supportsMobile: true,
      },
      {
        id: 'jwt-decoder',
        name: 'JWT Decoder',
        description: 'Decode and analyze JWT tokens. View header, payload, and signature.',
        category: 'cryptography',
        icon: '🔓',
        isPopular: true,
        path: '/tools/cryptography/jwt-decoder',
        component: 'JwtDecoder',
        supportsDesktop: true,
        supportsMobile: true,
      },
      {
        id: 'jwt-encoder',
        name: 'JWT Encoder',
        description: 'Create and encode JWT tokens with custom headers and payloads.',
        category: 'cryptography',
        icon: '🔒',
        isPopular: true,
        path: '/tools/cryptography/jwt-encoder',
        component: 'JwtEncoder',
        supportsDesktop: true,
        supportsMobile: true,
      },
      {
        id: 'hash-generator',
        name: 'Hash Generator',
        description: 'Generate cryptographic hashes using SHA-1, SHA-256, SHA-512, and SHA-3 algorithms with salt support',
        category: 'cryptography',
        icon: '🔐',
        isPopular: true,
        path: '/tools/cryptography/hash-generator',
        component: 'HashGenerator',
        supportsDesktop: true,
        supportsMobile: true,
      },
    ],
  },
  {
    id: 'encoders',
    name: 'Encoders & Decoders',
    icon: '🔄',
    color: 'orange',
    description: 'Text encoding and decoding utilities',
    tools: [
      {
        id: 'qr-code-generator',
        name: 'QR Code Generator',
        description: 'Generate QR codes for text, URLs, contacts, WiFi, SMS, and email with customizable options',
        category: 'encoders',
        icon: '📱',
        isPopular: true,
        path: '/tools/encoders/qr-code-generator',
        component: 'QrCodeGenerator',
        supportsDesktop: true,
        supportsMobile: true,
      },
      {
        id: 'qr-code-decoder',
        name: 'QR Code Decoder',
        description: 'Decode QR codes from uploaded images with support for multiple formats and structured data parsing',
        category: 'encoders',
        icon: '🔍',
        isPopular: true,
        path: '/tools/encoders/qr-code-decoder',
        component: 'QrCodeDecoder',
        supportsDesktop: true,
        supportsMobile: true,
      },
      {
        id: 'qr-code-scanner',
        name: 'QR Code Scanner',
        description: 'Scan QR codes using your device camera with real-time detection and instant results',
        category: 'encoders',
        icon: '📷',
        isPopular: true,
        path: '/tools/encoders/qr-code-scanner',
        component: 'QrCodeScanner',
        supportsDesktop: true,
        supportsMobile: true,
      },
      {
        id: 'url-encoder',
        name: 'URL Encoder',
        description: 'Encode URLs and text with multiple encoding types including URL, URI, and custom character sets',
        category: 'encoders',
        icon: '🔗',
        isPopular: true,
        path: '/tools/encoders/url-encoder',
        component: 'UrlEncoderTool',
        supportsDesktop: true,
        supportsMobile: true,
      },
      {
        id: 'url-decoder',
        name: 'URL Decoder',
        description: 'Decode URL-encoded text back to its original form with support for multiple encoding types',
        category: 'encoders',
        icon: '🔓',
        isPopular: true,
        path: '/tools/encoders/url-decoder',
        component: 'UrlDecoderTool',
        supportsDesktop: true,
        supportsMobile: true,
      },
      {
        id: 'base-encoder',
        name: 'Base Encoder/Decoder',
        description: 'Encode and decode text using Base64, Base32, Base16 (hex), Base85, and other base encodings',
        category: 'encoders',
        icon: '🔢',
        isPopular: true,
        path: '/tools/encoders/base-encoder',
        component: 'BaseEncoder',
        supportsDesktop: true,
        supportsMobile: true,
      },
    ],
  },
  {
    id: 'converters',
    name: 'Converters',
    icon: '🔀',
    color: 'teal',
    description: 'Data format conversion tools',
    tools: [
      {
        id: 'cron-parser',
        name: 'Cron Expression Parser',
        description: 'Build and parse cron expressions visually with a step-by-step form builder',
        category: 'converters',
        icon: '⏰',
        isPopular: true,
        path: '/tools/converters/cron-parser',
        component: 'CronParser',
        supportsDesktop: true,
        supportsMobile: true,
      },
      {
        id: 'data-format-converter',
        name: 'Data Format Converter',
        description: 'Convert between JSON, YAML, Python Dictionary, TypeScript Map, and XML formats',
        category: 'converters',
        icon: '🔄',
        isPopular: true,
        path: '/tools/converters/data-format-converter',
        component: 'DataFormatConverter',
        supportsDesktop: true,
        supportsMobile: true,
      },
      {
        id: 'timestamp-converter',
        name: 'Timestamp Converter',
        description: 'Convert between Unix timestamps, ISO 8601, RFC 2822, and other date formats across timezones',
        category: 'converters',
        icon: '🕐',
        isPopular: true,
        path: '/tools/converters/timestamp-converter',
        component: 'TimestampConverter',
        supportsDesktop: true,
        supportsMobile: true,
      },
      {
        id: 'list-converter',
        name: 'List Format Converter',
        description: 'Convert lists between different formats: line-by-line, comma-separated, JSON array, Python list, and more',
        category: 'converters',
        icon: '🔄',
        isPopular: true,
        path: '/tools/converters/list-converter',
        component: 'ListConverter',
        supportsDesktop: true,
        supportsMobile: true,
      },
      {
        id: 'schema-converter',
        name: 'Schema Converter',
        description: 'Convert between JSON Schema, Spark Schema, TypeScript, Python, SQL, and more',
        category: 'converters',
        icon: '📐',
        isPopular: true,
        path: '/tools/converters/schema-converter',
        component: 'SchemaConverter',
        supportsDesktop: true,
        supportsMobile: true,
        desktopRecommended: true,
      },
      {
        id: 'number-base-converter',
        name: 'Number Base Converter',
        description: 'Convert numbers between different bases (binary, octal, decimal, hexadecimal) with bit visualization and range calculator',
        category: 'converters',
        icon: '🔢',
        isPopular: true,
        path: '/tools/converters/number-base-converter',
        component: 'NumberBaseConverter',
        supportsDesktop: true,
        supportsMobile: true,
      },
    ],
  },
  {
    id: 'network',
    name: 'Network Tools',
    icon: '🌐',
    color: 'indigo',
    description: 'Network utilities and tools',
    tools: [
      {
        id: 'cidr-analyzer',
        name: 'CIDR Analyzer',
        description: 'Analyze CIDR notation and get detailed network information including subnets and statistics',
        category: 'network',
        icon: '🔍',
        isPopular: true,
        path: '/tools/network/cidr-analyzer',
        component: 'CidrAnalyzer',
        supportsDesktop: true,
        supportsMobile: true,
      },
      {
        id: 'ip-to-cidr-converter',
        name: 'IP to CIDR Converter',
        description: 'Convert an IP address to CIDR notation with network suggestions',
        category: 'network',
        icon: '🔗',
        isPopular: true,
        path: '/tools/network/ip-to-cidr-converter',
        component: 'IpToCidrConverter',
        supportsDesktop: true,
        supportsMobile: true,
      },
      {
        id: 'ip-checker',
        name: 'IP Address Lookup',
        description: 'Look up information about your current public IP address including location and network details',
        category: 'network',
        icon: '📡',
        isPopular: true,
        path: '/tools/network/ip-checker',
        component: 'IpChecker',
        supportsDesktop: true,
        supportsMobile: true,
      },
      {
        id: 'system-info',
        name: 'System Information',
        description: 'View detailed information about your browser, device, display, network, and system capabilities',
        category: 'network',
        icon: '💻',
        isPopular: true,
        path: '/tools/network/system-info',
        component: 'SystemInfo',
        supportsDesktop: true,
        supportsMobile: true,
      },
    ],
  },
  {
    id: 'utilities',
    name: 'Utilities',
    icon: '🛠️',
    color: 'purple',
    description: 'General utility tools and helpers',
    tools: [
      {
        id: 'list-comparison',
        name: 'List Comparison',
        description: 'Compare two lists of strings and numbers to find differences, intersections, unions, and more',
        category: 'utilities',
        icon: '📋',
        isPopular: true,
        path: '/tools/utilities/list-comparison',
        component: 'ListComparison',
        supportsDesktop: true,
        supportsMobile: true,
        desktopRecommended: true,
      },
      {
        id: 'json-path-finder',
        name: 'JSON Path Finder',
        description: 'Query and extract data from JSON using JSONPath expressions',
        category: 'utilities',
        icon: '🔍',
        isPopular: true,
        path: '/tools/utilities/json-path-finder',
        component: 'JsonPathFinder',
        supportsDesktop: true,
        supportsMobile: true,
      },
      {
        id: 'xml-path-finder',
        name: 'XML Path Finder',
        description: 'Query and extract data from XML using XPath expressions',
        category: 'utilities',
        icon: '🔍',
        isPopular: true,
        path: '/tools/utilities/xml-path-finder',
        component: 'XmlPathFinder',
        supportsDesktop: true,
        supportsMobile: true,
      },
      {
        id: 'yaml-path-finder',
        name: 'YAML Path Finder',
        description: 'Query and extract data from YAML using YAMLPath expressions',
        category: 'utilities',
        icon: '🔍',
        isPopular: true,
        path: '/tools/utilities/yaml-path-finder',
        component: 'YamlPathFinder',
        supportsDesktop: true,
        supportsMobile: true,
      },
      {
        id: 'json-schema-generator',
        name: 'JSON/YAML Schema Generator',
        description: 'Generate JSON Schema (Draft 7) from JSON or YAML data',
        category: 'utilities',
        icon: '📋',
        isPopular: true,
        path: '/tools/utilities/json-schema-generator',
        component: 'JsonSchemaGenerator',
        supportsDesktop: true,
        supportsMobile: true,
      },
    ],
  },
];

export const getPopularTools = () => {
  return toolCategories
    .flatMap(category => category.tools)
    .filter(tool => tool.isPopular);
};

export const getAllTools = () => {
  return toolCategories.flatMap(category => category.tools);
};

export const getToolById = (id: string) => {
  return getAllTools().find(tool => tool.id === id);
};

export const getCategoryById = (id: string) => {
  return toolCategories.find(category => category.id === id);
};

export const getCategories = () => {
  return toolCategories;
};

export const getTools = () => {
  return getAllTools();
};

export const searchTools = (query: string) => {
  const lowercaseQuery = query.toLowerCase();
  return getAllTools().filter(
    tool =>
      tool.name.toLowerCase().includes(lowercaseQuery) ||
      tool.description.toLowerCase().includes(lowercaseQuery)
  );
};



